version: '3.1'

services:
  app:
    container_name: sakai-lesson
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: sample-db
    environment:
        TZ: "Asia/Tokyo"  
    volumes:
        - .:/code
    ports:
     - "8080:8080"
    tty: true
    # networks: 
    #   - app-net

#   mysql:
#     container_name: sample-mysql
#     image: mysql:5.7
#     # restart: 'always'
#     hostname: sample-db
#     environment:
#       MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
#       MYSQL_DATABASE: 'test-db'
#       MYSQL_USER: 'root'
#       BIND-ADDRESS: 0.0.0.0
#     expose:
#       - '3306'
#     ports:
#       - "3306:3306"
#     tty: true
#     networks:
#       - app-net


# networks:
#   app-net:
#     driver: bridge